import React, { FC } from "react";
import styles from "./MainLayout.module.css";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { NavBar } from "../NavBar";
import { layoutType } from "./DarkLayout";

export const MainLayout: FC<layoutType>  = ({ children }) => {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Javier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <main className={styles.main}>{children}</main>

     
    </div>
  );
};
